/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author oscar
 */
public class VentanaPrincipal extends javax.swing.JFrame implements ActionListener{
    PanelLibro panelLib=new PanelLibro();
    PanelAlumno panelAlum=new PanelAlumno();
    PanelEncargado panelEnc=new PanelEncargado();
    PanelPrestamo panelPrest=new PanelPrestamo();
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        contenedor.add(panelLib);
        
        panelLib.setVisible(true);
        panelAlum.setVisible(false);
        panelEnc.setVisible(false);
        panelPrest.setVisible(false);
        deshabilitarBotones();
        
        boton_Lib.addActionListener(this);
        boton_Alum.addActionListener(this);
        boton_Enc.addActionListener(this);
        boton_Prest.addActionListener(this);
    }
    
    
    private void deshabilitarBotones(){
        if(panelLib.isVisible()){
            boton_Lib.setEnabled(false);
            boton_Alum.setEnabled(true);
            boton_Enc.setEnabled(true);
            boton_Prest.setEnabled(true);
        }else if(panelAlum.isVisible()){
            boton_Lib.setEnabled(true);
            boton_Alum.setEnabled(false);
            boton_Enc.setEnabled(true);
            boton_Prest.setEnabled(true);
        }
        else if(panelEnc.isVisible()){
            boton_Lib.setEnabled(true);
            boton_Alum.setEnabled(true);
            boton_Enc.setEnabled(false);
            boton_Prest.setEnabled(true);
        }else if(panelPrest.isVisible()){
            boton_Lib.setEnabled(true);
            boton_Alum.setEnabled(true);
            boton_Enc.setEnabled(true);
            boton_Prest.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boton_Enc = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        boton_Prest = new javax.swing.JButton();
        boton_Alum = new javax.swing.JButton();
        boton_Lib = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedor.setPreferredSize(new java.awt.Dimension(800, 400));
        contenedor.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de adiminstración de Biblioteca");
        jPanel2.add(jLabel1);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/biblioteca32x32.png"))); // NOI18N
        jLabel6.setMaximumSize(new java.awt.Dimension(60, 60));
        jLabel6.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanel2.add(jLabel6);

        contenedor.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/libros32x32.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(32, 32));
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/alumno32x32.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/encargado32x32.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        boton_Enc.setText("Encargado");
        jPanel4.add(boton_Enc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 105, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/prestamo32x32.png"))); // NOI18N
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        boton_Prest.setText("Préstamos");
        jPanel4.add(boton_Prest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 105, -1));

        boton_Alum.setText("Alumnos");
        jPanel4.add(boton_Alum, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 105, -1));

        boton_Lib.setText("Libros");
        boton_Lib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_LibActionPerformed(evt);
            }
        });
        jPanel4.add(boton_Lib, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 105, -1));

        jButton1.setText("Salir");
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        contenedor.add(jPanel4, java.awt.BorderLayout.LINE_START);

        getContentPane().add(contenedor, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_LibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_LibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boton_LibActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_Alum;
    private javax.swing.JButton boton_Enc;
    private javax.swing.JButton boton_Lib;
    private javax.swing.JButton boton_Prest;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        Object evt=ae.getSource();
        if(evt.equals(boton_Lib)){
            panelLib.setVisible(true);
            panelAlum.setVisible(false);
            panelEnc.setVisible(false);
            panelPrest.setVisible(false);
            contenedor.add(panelLib);
            contenedor.validate();
            deshabilitarBotones();
        }else if(evt.equals(boton_Alum)){
            panelLib.setVisible(false);
            panelAlum.setVisible(true);
            panelEnc.setVisible(false);
            panelPrest.setVisible(false);
            contenedor.add(panelAlum);
            contenedor.validate();
            deshabilitarBotones();
        }else if(evt.equals(boton_Enc)){
            panelLib.setVisible(false);
            panelAlum.setVisible(false);
            panelEnc.setVisible(true);
            panelPrest.setVisible(false);
            contenedor.add(panelEnc);
            contenedor.validate();
            deshabilitarBotones();
        }else if(evt.equals(boton_Prest)){
            panelLib.setVisible(false);
            panelAlum.setVisible(false);
            panelEnc.setVisible(false);
            panelPrest.setVisible(true);
            contenedor.add(panelPrest);
            contenedor.validate();
            deshabilitarBotones();
        }
    }
}
